#############################################################################
# Makefile for building: creaderasync
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  creaderasync.pro
# Template: app
# Command: /home/ubgel200/Qt/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile creaderasync.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_SERIALPORT_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.7/gcc_64/include -I../../../Qt/5.7/gcc_64/include/QtSerialPort -I../../../Qt/5.7/gcc_64/include/QtQuick -I../../../Qt/5.7/gcc_64/include/QtGui -I../../../Qt/5.7/gcc_64/include/QtQml -I../../../Qt/5.7/gcc_64/include/QtNetwork -I../../../Qt/5.7/gcc_64/include/QtCore -I. -I../../../Qt/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/ubgel200/Qt/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = creaderasync1.0.0
DISTDIR = /home/ubgel200/workspace/QT/creaderasync/.tmp/creaderasync1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/ubgel200/Qt/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/ubgel200/Qt/5.7/gcc_64/lib -lQt5SerialPort -lQt5Quick -L/usr/lib64 -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		serialportreader.cpp \
		textdata.cpp moc_serialportreader.cpp \
		moc_textdata.cpp
OBJECTS       = main.o \
		serialportreader.o \
		textdata.o \
		moc_serialportreader.o \
		moc_textdata.o
DIST          = Display.qml \
		../../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		creaderasync.pro serialportreader.h \
		textdata.h main.cpp \
		serialportreader.cpp \
		textdata.cpp
QMAKE_TARGET  = creaderasync
DESTDIR       = 
TARGET        = creaderasync


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: creaderasync.pro ../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		creaderasync.pro \
		../../../Qt/5.7/gcc_64/lib/libQt5SerialPort.prl \
		../../../Qt/5.7/gcc_64/lib/libQt5Quick.prl \
		../../../Qt/5.7/gcc_64/lib/libQt5Gui.prl \
		../../../Qt/5.7/gcc_64/lib/libQt5Qml.prl \
		../../../Qt/5.7/gcc_64/lib/libQt5Network.prl \
		../../../Qt/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile creaderasync.pro
../../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/gcc_64/mkspecs/common/unix.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/linux.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/5.7/gcc_64/mkspecs/qconfig.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/toolchain.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/qt.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/resources.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/moc.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/lex.prf:
creaderasync.pro:
../../../Qt/5.7/gcc_64/lib/libQt5SerialPort.prl:
../../../Qt/5.7/gcc_64/lib/libQt5Quick.prl:
../../../Qt/5.7/gcc_64/lib/libQt5Gui.prl:
../../../Qt/5.7/gcc_64/lib/libQt5Qml.prl:
../../../Qt/5.7/gcc_64/lib/libQt5Network.prl:
../../../Qt/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile creaderasync.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents serialportreader.h textdata.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp serialportreader.cpp textdata.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_serialportreader.cpp moc_textdata.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_serialportreader.cpp moc_textdata.cpp
moc_serialportreader.cpp: ../../../Qt/5.7/gcc_64/include/QtSerialPort/QSerialPort \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialport.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QTextStream \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QByteArray \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		serialportreader.h \
		../../../Qt/5.7/gcc_64/bin/moc
	/home/ubgel200/Qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/ubgel200/Qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/ubgel200/workspace/QT/creaderasync -I/home/ubgel200/Qt/5.7/gcc_64/include -I/home/ubgel200/Qt/5.7/gcc_64/include/QtSerialPort -I/home/ubgel200/Qt/5.7/gcc_64/include/QtQuick -I/home/ubgel200/Qt/5.7/gcc_64/include/QtGui -I/home/ubgel200/Qt/5.7/gcc_64/include/QtQml -I/home/ubgel200/Qt/5.7/gcc_64/include/QtNetwork -I/home/ubgel200/Qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include serialportreader.h -o moc_serialportreader.cpp

moc_textdata.cpp: ../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Qt/5.7/gcc_64/include/QtCore/QString \
		textdata.h \
		../../../Qt/5.7/gcc_64/bin/moc
	/home/ubgel200/Qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/ubgel200/Qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/ubgel200/workspace/QT/creaderasync -I/home/ubgel200/Qt/5.7/gcc_64/include -I/home/ubgel200/Qt/5.7/gcc_64/include/QtSerialPort -I/home/ubgel200/Qt/5.7/gcc_64/include/QtQuick -I/home/ubgel200/Qt/5.7/gcc_64/include/QtGui -I/home/ubgel200/Qt/5.7/gcc_64/include/QtQml -I/home/ubgel200/Qt/5.7/gcc_64/include/QtNetwork -I/home/ubgel200/Qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include textdata.h -o moc_textdata.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp serialportreader.h \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/QSerialPort \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialport.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QTextStream \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QByteArray \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		textdata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Qt/5.7/gcc_64/include/QtCore/QString \
		../../../Qt/5.7/gcc_64/include/QtCore/QCoreApplication \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QStringList \
		../../../Qt/5.7/gcc_64/include/QtQuick/QtQuick \
		../../../Qt/5.7/gcc_64/include/QtQuick/QtQuickDepends \
		../../../Qt/5.7/gcc_64/include/QtCore/QtCore \
		../../../Qt/5.7/gcc_64/include/QtCore/QtCoreDepends \
		../../../Qt/5.7/gcc_64/include/QtCore/qabstractanimation.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qanimationgroup.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpauseanimation.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpropertyanimation.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariantanimation.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qeasingcurve.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextcodec.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qendian.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlibraryinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbuffer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdir.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdiriterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfileselector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlockfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qloggingcategory.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocess.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qresource.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsavefile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsettings.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstandardpaths.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstorageinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtemporarydir.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtemporaryfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlistmodel.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qjsonarray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qjsonvalue.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qjsondocument.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qjsonobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmath.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetaobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmimedata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedmemory.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsignalmapper.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsocketnotifier.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtranslator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qwineventnotifier.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmimedatabase.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmimetype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfactoryinterface.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlibrary.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qplugin.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpluginloader.h \
		../../../Qt/5.7/gcc_64/include/QtCore/quuid.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qabstractstate.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qabstracttransition.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qeventtransition.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfinalstate.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhistorystate.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsignaltransition.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstate.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstatemachine.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qexception.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfuture.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfutureinterface.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrunnable.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qresultstore.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfuturewatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qreadwritelock.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsemaphore.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qthread.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qthreadpool.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qthreadstorage.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qwaitcondition.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydataops.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydatapointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbitarray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcollator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcommandlineoption.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcommandlineparser.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qelapsedtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlinkedlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qqueue.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregularexpression.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstack.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimeline.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimezone.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversionnumber.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qxmlstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtcoreversion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QtGui \
		../../../Qt/5.7/gcc_64/include/QtGui/QtGuiDepends \
		../../../Qt/5.7/gcc_64/include/QtGui/qaccessible.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qaccessiblebridge.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qaccessibleobject.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qaccessibleplugin.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qbitmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qiconengine.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qiconengineplugin.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimageiohandler.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimagereader.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimagewriter.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmovie.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpicture.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpictureformatplugin.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmapcache.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qstandarditemmodel.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qclipboard.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qdrag.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericplugin.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericpluginfactory.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qoffscreensurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QPaintDeviceWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevicewindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtGui/QPaintDevice \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLContext \
		../../../Qt/5.7/gcc_64/include/QtGui/QImage \
		../../../Qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrasterwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qscreen.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QList \
		../../../Qt/5.7/gcc_64/include/QtCore/QSize \
		../../../Qt/5.7/gcc_64/include/QtCore/QSizeF \
		../../../Qt/5.7/gcc_64/include/QtGui/QTransform \
		../../../Qt/5.7/gcc_64/include/QtGui/qsessionmanager.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qstylehints.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglbuffer.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengldebug.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglextrafunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglpixeltransferoptions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengltexture.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengltimerquery.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qbackingstore.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpagedpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpagelayout.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpagesize.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintengine.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainter.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpdfwriter.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextlayout.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qglyphrun.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrawfont.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qfontdatabase.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextdocument.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qstatictext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextobject.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextdocumentfragment.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextdocumentwriter.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextlist.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtexttable.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qdesktopservices.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvalidator.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtguiversion.h \
		../../../Qt/5.7/gcc_64/include/QtQml/QtQml \
		../../../Qt/5.7/gcc_64/include/QtQml/QtQmlDepends \
		../../../Qt/5.7/gcc_64/include/QtNetwork/QtNetwork \
		../../../Qt/5.7/gcc_64/include/QtNetwork/QtNetworkDepends \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qabstractnetworkcache.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QUrl \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qhttpmultipart.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QIODevice \
		../../../Qt/5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qssl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QFlags \
		../../../Qt/5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QtGlobal \
		../../../Qt/5.7/gcc_64/include/QtCore/QMetaType \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkcookie.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkcookiejar.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkdiskcache.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkconfigmanager.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkconfiguration.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworksession.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkinterface.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qhostaddress.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qauthenticator.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qdnslookup.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qhostinfo.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qnetworkproxy.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qlocalserver.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qlocalsocket.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qtcpserver.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qudpsocket.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslcertificateextension.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslcipher.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslellipticcurve.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QHash \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qsslkey.h \
		../../../Qt/5.7/gcc_64/include/QtNetwork/qtnetworkversion.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmldebug.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qjsengine.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qjsvalue.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qjsvalueiterator.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqml.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmllist.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlabstracturlinterceptor.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlengine.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlerror.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlcomponent.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlcontext.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlexpression.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlscriptstring.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlextensioninterface.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlextensionplugin.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlfile.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlfileselector.h \
		../../../Qt/5.7/gcc_64/include/QtQml/QQmlEngine \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlincubator.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlinfo.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlproperty.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qqmlpropertymap.h \
		../../../Qt/5.7/gcc_64/include/QtQml/qtqmlversion.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickframebufferobject.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/QQuickItem \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickitem.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickitemgrabresult.h \
		../../../Qt/5.7/gcc_64/include/QtQml/QJSValue \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickpainteditem.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickrendercontrol.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquicktextdocument.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QTextDocument \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickview.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickwindow.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qquickimageprovider.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgabstractrenderer.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgnode.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsggeometry.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QRectF \
		../../../Qt/5.7/gcc_64/include/QtGui/QMatrix4x4 \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgmaterial.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgengine.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgflatcolormaterial.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgsimplematerial.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgsimplerectnode.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgsimpletexturenode.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgtexturematerial.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgtexture.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgtextureprovider.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qsgvertexcolormaterial.h \
		../../../Qt/5.7/gcc_64/include/QtQuick/qtquickversion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QGuiApplication \
		../../../Qt/5.7/gcc_64/include/QtQml/QQmlApplicationEngine
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

serialportreader.o: serialportreader.cpp serialportreader.h \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/QSerialPort \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialport.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QTextStream \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QByteArray \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/QCoreApplication \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialportreader.o serialportreader.cpp

textdata.o: textdata.cpp textdata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Qt/5.7/gcc_64/include/QtCore/QString \
		serialportreader.h \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/QSerialPort \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialport.h \
		../../../Qt/5.7/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QTextStream \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textdata.o textdata.cpp

moc_serialportreader.o: moc_serialportreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialportreader.o moc_serialportreader.cpp

moc_textdata.o: moc_textdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textdata.o moc_textdata.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/ubgel200/Qt/Examples/Qt-5.7/serialport/creaderasync || mkdir -p $(INSTALL_ROOT)/home/ubgel200/Qt/Examples/Qt-5.7/serialport/creaderasync
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/ubgel200/Qt/Examples/Qt-5.7/serialport/creaderasync/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/ubgel200/Qt/Examples/Qt-5.7/serialport/creaderasync/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/ubgel200/Qt/Examples/Qt-5.7/serialport/creaderasync/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

